require:
  - rubocop-performance
  - rubocop-rake

inherit_gem:
  onkcop:
    - "config/rubocop.yml"
    - "config/rspec.yml"
    - "config/performance.yml"

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/SharedExamples:
  Enabled: false
