cure_summer: &cure_summer
  girl_name:    cure_summer
  human_name:   夏海まなつ
  precure_name: キュアサマー
  cast_name:    ファイルーズあい
  color:        white
  created_date: 2021-02-28 # episode 1
  birthday:     8/1
  transform_message: |-
    プリキュア！トロピカルチェンジ！
    レッツメイク！キャッチ！
    チーク！
    アイズ！
    ヘアー！
    リップ！
    ドレス！
    ときめく常夏！キュアサマー！
    はぁー！
    ${random_transform_word}
    トロピカル～ジュ！プリキュア！
  random_transform_words: &random_transform_words
    - 4人揃って！
    - 今日も元気だ！
    - よく食べよく寝る！
    - エキストラだよ！
    - 笑顔は100点！
    - 雨にも負けない！
    - 噂も吹き飛ぶ！
    - 悩みも吹き飛ぶ！
    - よいこの友達！
    - 今日も元気だ！
    - 5人揃って！
    - 年中無休だ！
    - 一人迷子だ！
    - お祭り大好き！
    - 転んで泣かない！
    - いいとこ見せたい！
    - 光る5つ星！
    - 今日も元気だ！
    - メイクは気合だ！
    - 6人揃って！
    - 雪の国でも！
    - 子どももなれるよ！
    - 今日も元気だ！
    - 仮装じゃないよ！
    - 今日も元気だ！
    - 今日も本気だ！
    - 燃えるど根性！
    - 今日も元気だ！
    - 全速前進！
    - 絶対負けない！
    - あっという間に！
  # extra_names:
  attack_messages:
    - |-
      ハートルージュロッド！
      プリキュア！おてんとサマーストライク！
      ビクトリー！
  transform_calls:
    - tropical_change
summer:
  <<: *cure_summer

cure_coral: &cure_coral
  girl_name:    cure_coral
  human_name:   涼村さんご
  precure_name: キュアコーラル
  cast_name:    花守ゆみり
  color:        purple
  created_date: 2021-03-14 # episode 3
  birthday:     5/9
  transform_message: |-
    プリキュア！トロピカルチェンジ！
    レッツメイク！キャッチ！
    リップ！
    アイズ！
    ヘアー！
    チーク！
    ドレス！
    きらめく宝石！キュアコーラル！
    はぁー！
    ${random_transform_word}
    トロピカル～ジュ！プリキュア！
  random_transform_words: *random_transform_words
  # extra_names:
  attack_messages:
    - |-
      ハートルージュロッド！
      プリキュア！もこもこコーラルディフュージョン！
      ビクトリー！
  transform_calls:
    - tropical_change
coral:
  <<: *cure_coral

cure_papaya: &cure_papaya
  girl_name:    cure_papaya
  human_name:   一ノ瀬みのり
  precure_name: キュアパパイア
  cast_name:    石川由依
  color:        yellow
  created_date: 2021-03-21 # episode 4
  birthday:     11/21
  transform_message: |-
    プリキュア！トロピカルチェンジ！
    レッツメイク！キャッチ！
    チーク！
    リップ！
    ヘアー！
    アイズ！
    ドレス！
    ひらめく果実！キュアパパイア！
    はぁー！
    ${random_transform_word}
    トロピカル～ジュ！プリキュア！
  random_transform_words: *random_transform_words
  # extra_names:
  attack_messages:
    - |-
      ハートルージュロッド！
      プリキュア！ぱんぱかパパイアショット！
      ビクトリー！
  transform_calls:
    - tropical_change
papaya:
  <<: *cure_papaya

cure_flamingo: &cure_flamingo
  girl_name:    cure_flamingo
  human_name:   滝沢あすか
  precure_name: キュアフラミンゴ
  cast_name:    瀬戸麻沙美
  color:        red
  created_date: 2021-03-28 # episode 5
  birthday:     10/15
  transform_message: |-
    プリキュア！トロピカルチェンジ！
    レッツメイク！キャッチ！
    チーク！
    アイズ！
    リップ！
    ヘアー！
    ドレス！
    はためく翼！キュアフラミンゴ！
    はぁー！
    ${random_transform_word}
    トロピカル～ジュ！プリキュア！
  random_transform_words: *random_transform_words
  # extra_names:
  attack_messages:
    - |-
      ハートルージュロッド！
      プリキュア！ぶっとびフラミンゴスマッシュ！
      ビクトリー！
  transform_calls:
    - tropical_change
flamingo:
  <<: *cure_flamingo

cure_lamer: &cure_lamer
  girl_name:       cure_lamer
  human_name:      ローラ・ラメール
  human_full_name: ローラ・アポロドーロス・ヒュギーヌス・ラメール
  precure_name:    キュアラメール
  cast_name:       日高里菜
  color:           blue
  created_date:    2021-06-20 # episode 17
  birthday:        6/30
  transform_message: |-
    プリキュア！トロピカルチェンジ！
    レッツメイク！キャッチ！
    フェイス！
    ネイル！
    ドレス！
    ゆらめく大海原！キュアラメール！
    はぁー！
    ${random_transform_word}
    トロピカル～ジュ！プリキュア！
  random_transform_words: *random_transform_words
  # extra_names:
  attack_messages:
    - |-
      プリキュア！くるくるラメールストリーム！
      ビクトリー！
  transform_calls:
    - tropical_change
lamer:
  <<: *cure_lamer
